[versions]
spring-boot = "4.0.0"
jakarta-persistence = "3.2.0"
jakarta-validation = "4.0.0-M1"
hibernate = "7.2.0.Final"
h2 = "2.4.240"
jackson = "2.20.1"
javafx = "26-ea+19"
junit = "6.1.0-M1"
lombok = "1.18.42"
jakarta-transaction = "2.0.1"
hikaricp = "5.0.1"
postgresql = "42.6.0"

[libraries]
jakarta-persistence-api = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
hibernate-core = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }
jakarta-transaction-api = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "jakarta-transaction" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }